/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum4;

/**
 *
 * @author Bagaskara
 */
public class Soal4 extends javax.swing.JFrame {

    /**
     * Creates new form Soal4
     */
    public Soal4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputNilai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        choose1 = new javax.swing.JRadioButton();
        choose2 = new javax.swing.JRadioButton();
        choose3 = new javax.swing.JRadioButton();
        choose4 = new javax.swing.JRadioButton();
        choose5 = new javax.swing.JRadioButton();
        choose6 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        output = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Konversi Nilai Temperatur");

        jLabel2.setText("Masukan Nilai :");

        inputNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNilaiActionPerformed(evt);
            }
        });

        jLabel3.setText("Dari ");

        jLabel4.setText("Ke");

        buttonGroup1.add(choose1);
        choose1.setText("Celcius");

        buttonGroup1.add(choose2);
        choose2.setText("Farenheit");

        buttonGroup1.add(choose3);
        choose3.setText("Kelvin");

        buttonGroup2.add(choose4);
        choose4.setText("Celcius");
        choose4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(choose5);
        choose5.setText("Farenheit");

        buttonGroup2.add(choose6);
        choose6.setText("Kelvin");

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        output.setBackground(new java.awt.Color(0, 0, 255));
        output.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        output.setForeground(new java.awt.Color(255, 255, 255));
        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });

        ket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(output, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(choose3)
                            .addComponent(choose2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(294, 294, 294)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(61, 61, 61)
                                    .addComponent(inputNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(choose1)
                                .addGap(242, 242, 242)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(choose5)
                                    .addComponent(choose4)
                                    .addComponent(choose6)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton1)
                        .addGap(94, 94, 94)
                        .addComponent(jButton2)))
                .addContainerGap(116, Short.MAX_VALUE))
            .addComponent(ket, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choose1)
                    .addComponent(choose4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choose2)
                    .addComponent(choose5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(choose3)
                    .addComponent(choose6))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(42, 42, 42)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ket, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNilaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNilaiActionPerformed

    private void choose4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choose4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (inputNilai.getText().isEmpty()) {
            ket.setText("Anda Belum Input Nilai");
        } else if (choose1.isSelected()) {
            double nilai = Double.parseDouble(inputNilai.getText());
            if (choose4.isSelected()) {
                output.setText(inputNilai.getText() + " C");
            } else if (choose5.isSelected()) {
                double hasil = (9 / 5) * nilai + 32;
                output.setText(String.format("%.2f", hasil) + " F");
            } else if (choose6.isSelected()) {
                double hasil2 = nilai + 273.15;
                output.setText(String.format("%.2f", hasil2) + " K");
            }
        } else if (choose2.isSelected()) {
            double nilai = Double.parseDouble(inputNilai.getText());
            if (choose4.isSelected()) {
                double hasil3 = (5.0 / 9.0) * (nilai - 32.0);
                output.setText(String.format("%.2f", hasil3) + " C");
            } else if (choose5.isSelected()) {
                output.setText(inputNilai.getText() + " F");
            } else if (choose6.isSelected()) {
                double hasil4 = (5.0 / 9.0) * (nilai - 32.0) + 273.15;
                output.setText(String.format("%.2f", hasil4) + " K");
            }
        } else if (choose3.isSelected()) {
            double nilai = Double.parseDouble(inputNilai.getText());
            if (choose4.isSelected()) {
                double hasil5 = nilai - 273.15;
                output.setText(String.format("%.2f", hasil5) + " C");
            } else if (choose5.isSelected()) {
                double hasil6 = (9 / 5) * (nilai - 273.15) + 32;
                output.setText(String.format("%.2f", hasil6) + " F");
            } else if (choose6.isSelected()) {
                output.setText(inputNilai.getText() + " K");
            }
        } else {
            ket.setText("Anda Belum Memilih Temperatur");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        output.setText("");
        inputNilai.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton choose1;
    private javax.swing.JRadioButton choose2;
    private javax.swing.JRadioButton choose3;
    private javax.swing.JRadioButton choose4;
    private javax.swing.JRadioButton choose5;
    private javax.swing.JRadioButton choose6;
    private javax.swing.JTextField inputNilai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel ket;
    private javax.swing.JTextField output;
    // End of variables declaration//GEN-END:variables
}
