/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UTPraktikum;

import javax.swing.JOptionPane;

/**
 *
 * @author Bagaskara
 */
public class UTPraktikum extends javax.swing.JFrame {

    /**
     * Creates new form UTPraktikum2
     */
    public UTPraktikum() {
        initComponents();
        this.setExtendedState(UTPraktikum.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        inputBulan = new javax.swing.JTextField();
        inputTahun = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        choose1 = new javax.swing.JRadioButton();
        choose2 = new javax.swing.JRadioButton();
        choose3 = new javax.swing.JRadioButton();
        check = new javax.swing.JCheckBox();
        output = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputTanggal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        inputBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBulanActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Silahkan Masukan Tanggal Penerbangan (Batas Sampai April 2024)");

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setText("Clear Selection");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(choose1);
        choose1.setText("Jakarta");
        choose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(choose2);
        choose2.setText("Surabaya");
        choose2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choose2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(choose3);
        choose3.setText("Bali");

        check.setText("Saya Telah Yakin Dengan Pilihan");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        output.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PEMBELIAN TIKET PESAWAT DARI BANJARMASIN");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Silahkan Pilih Kota Tujuan Anda");

        jLabel3.setText("Masukan Tanggal :");

        jLabel4.setText("Masukan Bulan : ");

        jLabel5.setText("Masukan Tahun :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(148, 148, 148)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputTanggal)
                    .addComponent(inputBulan)
                    .addComponent(inputTahun, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(output, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(check)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(176, 176, 176))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(choose2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(choose1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(choose3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(choose1)
                .addGap(18, 18, 18)
                .addComponent(choose2)
                .addGap(18, 18, 18)
                .addComponent(choose3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check)
                .addGap(30, 30, 30)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBulanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (inputTahun.getText().isEmpty() || inputBulan.getText().isEmpty() || inputTanggal.getText().isEmpty()) {
            output.setText("Terdapat Keterangan Yang Belum Anda Isi");
        } else {
            int tahun = Integer.parseInt(inputTahun.getText());
            int bulan = Integer.parseInt(inputBulan.getText());
            int tanggal = Integer.parseInt(inputTanggal.getText());
            if (check.isSelected()) {
                if (choose1.isSelected()) {
                    if (tahun == 2023) {
                        if (bulan == 5 || bulan == 7 || bulan == 8 || bulan == 10 || bulan == 12) {
                            if (tanggal > 0 && tanggal < 32) {
                                UTPraktikumJakarta jakarta = new UTPraktikumJakarta();
                                jakarta.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 6 || bulan == 9 || bulan == 11) {
                            if (tanggal > 0 && tanggal < 31) {
                                UTPraktikumJakarta jakarta = new UTPraktikumJakarta();
                                jakarta.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 1 || bulan == 2 || bulan == 3 || bulan == 4) {
                            output.setText("Anda Tidak Dapat Memilih Bulan Yang Sudah Lewat");
                        } else {
                            output.setText("Bulan Yang Anda Input Invalid");
                        }
                    } else if (tahun == 2024) {
                        if (bulan == 2) {
                            if (tanggal > 0 && tanggal < 30) {
                                UTPraktikumJakarta jakarta = new UTPraktikumJakarta();
                                jakarta.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 1 || bulan == 3) {
                            if (tanggal > 0 && tanggal < 32) {
                                UTPraktikumJakarta jakarta = new UTPraktikumJakarta();
                                jakarta.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 4) {
                            if (tanggal > 0 && tanggal < 31) {
                                UTPraktikumJakarta jakarta = new UTPraktikumJakarta();
                                jakarta.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan > 4 && bulan < 13) {
                            output.setText("Tiket Belum Tersedia, Batas Pemesanan Hingga Bulan April 2024");
                        } else {
                            output.setText("Bulan Yang Anda Input Invalid");
                        }
                    } else {
                        output.setText("Tahun Invalid, Anda Hanya Bisa Memesan Tiket Hingga April 2024");
                    }
                } else if (choose2.isSelected()) {
                    if (tahun == 2023) {
                        if (bulan == 5 || bulan == 7 || bulan == 8 || bulan == 10 || bulan == 12) {
                            if (tanggal > 0 && tanggal < 32) {
                                UTPraktikumSurabaya surabaya = new UTPraktikumSurabaya();
                                surabaya.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 6 || bulan == 9 || bulan == 11) {
                            if (tanggal > 0 && tanggal < 31) {
                                UTPraktikumSurabaya surabaya = new UTPraktikumSurabaya();
                                surabaya.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 1 || bulan == 2 || bulan == 3 || bulan == 4) {
                            output.setText("Anda Tidak Dapat Memilih Bulan Yang Sudah Lewat");
                        } else {
                            output.setText("Bulan Yang Anda Input Invalid");
                        }
                    } else if (tahun == 2024) {
                        if (bulan == 2) {
                            if (tanggal > 0 && tanggal < 30) {
                                UTPraktikumSurabaya surabaya = new UTPraktikumSurabaya();
                                surabaya.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 1 || bulan == 3) {
                            if (tanggal > 0 && tanggal < 32) {
                                UTPraktikumSurabaya surabaya = new UTPraktikumSurabaya();
                                surabaya.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 4) {
                            if (tanggal > 0 && tanggal < 31) {
                                UTPraktikumSurabaya surabaya = new UTPraktikumSurabaya();
                                surabaya.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan > 4 && bulan < 13) {
                            output.setText("Tiket Belum Tersedia, Batas Pemesanan Hingga Bulan April 2024");
                        } else {
                            output.setText("Bulan Yang Anda Input Invalid");
                        }
                    } else {
                        output.setText("Tahun Invalid, Anda Hanya Bisa Memesan Tiket Hingga April 2024");
                    }
                } else if (choose3.isSelected()) {
                    if (tahun == 2023) {
                        if (bulan == 5 || bulan == 7 || bulan == 8 || bulan == 10 || bulan == 12) {
                            if (tanggal > 0 && tanggal < 32) {
                                UTPraktikumBali bali = new UTPraktikumBali();
                                bali.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 6 || bulan == 9 || bulan == 11) {
                            if (tanggal > 0 && tanggal < 31) {
                                UTPraktikumBali bali = new UTPraktikumBali();
                                bali.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 1 || bulan == 2 || bulan == 3 || bulan == 4) {
                            output.setText("Anda Tidak Dapat Memilih Bulan Yang Sudah Lewat");
                        } else {
                            output.setText("Bulan Yang Anda Input Invalid");
                        }
                    } else if (tahun == 2024) {
                        if (bulan == 2) {
                            if (tanggal > 0 && tanggal < 30) {
                                UTPraktikumBali bali = new UTPraktikumBali();
                                bali.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 1 || bulan == 3) {
                            if (tanggal > 0 && tanggal < 32) {
                                UTPraktikumBali bali = new UTPraktikumBali();
                                bali.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan == 4) {
                            if (tanggal > 0 && tanggal < 31) {
                                UTPraktikumBali bali = new UTPraktikumBali();
                                bali.setVisible(true);
                                this.dispose();
                            } else {
                                output.setText("Tanggal Tidak Tersedia");
                            }
                        } else if (bulan > 4 && bulan < 13) {
                            output.setText("Tiket Belum Tersedia, Batas Pemesanan Hingga Bulan April 2024");
                        } else {
                            output.setText("Bulan Yang Anda Input Invalid");
                        }
                    } else {
                        output.setText("Tahun Invalid, Anda Hanya Bisa Memesan Tiket Hingga April 2024");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Silahkan Validasi Pilihan Anda");
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        buttonGroup1.clearSelection();
        inputTanggal.setText("");
        inputBulan.setText("");
        inputTahun.setText("");
        check.setSelected(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void choose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choose1ActionPerformed

    private void choose2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choose2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choose2ActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed

    }//GEN-LAST:event_checkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UTPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UTPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UTPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UTPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UTPraktikum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox check;
    private javax.swing.JRadioButton choose1;
    private javax.swing.JRadioButton choose2;
    private javax.swing.JRadioButton choose3;
    private javax.swing.JTextField inputBulan;
    private javax.swing.JTextField inputTahun;
    private javax.swing.JTextField inputTanggal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel output;
    // End of variables declaration//GEN-END:variables
}
