package middleproject;

import javax.swing.JOptionPane;

public class bali extends javax.swing.JFrame {

    /**
     * Creates new form bali
     */
    public bali() {
        initComponents();
        this.setExtendedState(FlightBookingApp.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        departureTimeLabel1 = new javax.swing.JLabel();
        departureTimeLabel2 = new javax.swing.JLabel();
        departureTimeLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        passengerCountLabel = new javax.swing.JLabel();
        passengerCountField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        orderDetailsLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        clearSelectionButton = new javax.swing.JButton();
        garudaRadioButton = new javax.swing.JRadioButton();
        confirmCheckBox = new javax.swing.JCheckBox();
        lionAirRadioButton = new javax.swing.JRadioButton();
        notesLabel = new javax.swing.JLabel();
        chooseAirlineLabel = new javax.swing.JLabel();
        payButton = new javax.swing.JButton();
        citilinkRadioButton = new javax.swing.JRadioButton();
        batikAirRadioButton = new javax.swing.JRadioButton();
        superAirJetRadioButton = new javax.swing.JRadioButton();
        priceField1 = new javax.swing.JTextField();
        priceField2 = new javax.swing.JTextField();
        priceField3 = new javax.swing.JTextField();
        priceField4 = new javax.swing.JTextField();
        priceField5 = new javax.swing.JTextField();
        departureTimeLabel4 = new javax.swing.JLabel();
        departureTimeLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        departureTimeLabel1.setText("15:05 WITA - 16:20 WITA");

        departureTimeLabel2.setText("06:00 WITA - 07:40 WITA");

        departureTimeLabel3.setText("07:30 WITA - 09:00 WITA");

        backButton.setBackground(new java.awt.Color(255, 255, 51));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        passengerCountLabel.setText("Enter Number of Passengers:");

        submitButton.setBackground(new java.awt.Color(0, 255, 0));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        orderDetailsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("FLIGHT TICKET BOOKING FROM BANJARMASIN TO BALI");

        clearSelectionButton.setBackground(new java.awt.Color(255, 0, 0));
        clearSelectionButton.setText("Clear Selection");
        clearSelectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSelectionButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(garudaRadioButton);
        garudaRadioButton.setText("Garuda Indonesia GA-540");

        confirmCheckBox.setText("Selection and Details Are Correct");

        buttonGroup1.add(lionAirRadioButton);
        lionAirRadioButton.setText("Lion Air JT-340");

        notesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        chooseAirlineLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseAirlineLabel.setText("Please Select an Available Airline");

        payButton.setBackground(new java.awt.Color(0, 255, 0));
        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(citilinkRadioButton);
        citilinkRadioButton.setText("Citilink QG-488");
        citilinkRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citilinkRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(batikAirRadioButton);
        batikAirRadioButton.setText("Batik Air ID-6218");

        buttonGroup1.add(superAirJetRadioButton);
        superAirJetRadioButton.setText("Super Air Jet UA-633");

        priceField1.setText("Rp.1,845,000");

        priceField2.setText("Rp.1,198,000");

        priceField3.setText("Rp.1,281,000");
        priceField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceField3ActionPerformed(evt);
            }
        });

        priceField4.setText("Rp.1,512,000");

        priceField5.setText("Rp.1,169,000");

        departureTimeLabel4.setText("14:00 WITA - 15:30 WITA");

        departureTimeLabel5.setText("12:30 WITA - 14:10 WITA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(chooseAirlineLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departureTimeLabel4)
                            .addComponent(garudaRadioButton)
                            .addComponent(lionAirRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departureTimeLabel5)
                            .addComponent(citilinkRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departureTimeLabel1)
                            .addComponent(batikAirRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departureTimeLabel2)
                            .addComponent(superAirJetRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(departureTimeLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priceField4)
                            .addComponent(priceField3)
                            .addComponent(priceField1)
                            .addComponent(priceField5)
                            .addComponent(priceField2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(116, 116, 116)
                        .addComponent(submitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearSelectionButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(passengerCountLabel)
                        .addGap(44, 44, 44)
                        .addComponent(passengerCountField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(153, 153, 153))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(orderDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(notesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(confirmCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(payButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseAirlineLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(garudaRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departureTimeLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lionAirRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departureTimeLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(citilinkRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departureTimeLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(batikAirRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departureTimeLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(superAirJetRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departureTimeLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(priceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passengerCountLabel)
                    .addComponent(passengerCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(submitButton)
                    .addComponent(clearSelectionButton))
                .addGap(18, 18, 18)
                .addComponent(orderDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notesLabel)
                .addGap(18, 18, 18)
                .addComponent(payButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // Your submission logic here
        if (garudaRadioButton.isSelected()) {
            orderDetailsLabel.setText("Garuda Indonesia GA-540");
        } else if (lionAirRadioButton.isSelected()) {
            orderDetailsLabel.setText("Lion Air JT-340");
        } else if (citilinkRadioButton.isSelected()) {
            orderDetailsLabel.setText("Citilink QG-488");
        } else if (batikAirRadioButton.isSelected()) {
            orderDetailsLabel.setText("Batik Air ID-6218");
        } else if (superAirJetRadioButton.isSelected()) {
            orderDetailsLabel.setText("Super Air Jet UA-633");
        } else {
            JOptionPane.showMessageDialog(this, "Please select an airline.");
            return;
        }
        if (passengerCountField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the number of passengers.");
            return;
        }
        int passengerCount = Integer.parseInt(passengerCountField.getText());
        if (passengerCount < 1) {
            JOptionPane.showMessageDialog(this, "The number of passengers must be at least 1.");
            return;
        }
        if (!confirmCheckBox.isSelected()) {
            JOptionPane.showMessageDialog(this, "Please confirm that your selection and details are correct.");
            return;
        }
        // Process the order
        JOptionPane.showMessageDialog(this, "Order submitted successfully!");
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Your back button logic here
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void clearSelectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSelectionButtonActionPerformed
        // Clear all selections
        buttonGroup1.clearSelection();
        orderDetailsLabel.setText("");
        passengerCountField.setText("");
        confirmCheckBox.setSelected(false);
    }//GEN-LAST:event_clearSelectionButtonActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // Your payment logic here
        JOptionPane.showMessageDialog(this, "Payment successful!");
    }//GEN-LAST:event_payButtonActionPerformed

    private void citilinkRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citilinkRadioButtonActionPerformed
        // Your Citilink logic here
    }//GEN-LAST:event_citilinkRadioButtonActionPerformed

    private void priceField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceField3ActionPerformed
        // Your price field logic here
    }//GEN-LAST:event_priceField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightBookingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightBookingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightBookingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightBookingApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightBookingApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton batikAirRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearSelectionButton;
    private javax.swing.JCheckBox confirmCheckBox;
    private javax.swing.JRadioButton citilinkRadioButton;
    private javax.swing.JLabel chooseAirlineLabel;
    private javax.swing.JLabel departureTimeLabel1;
    private javax.swing.JLabel departureTimeLabel2;
    private javax.swing.JLabel departureTimeLabel3;
    private javax.swing.JLabel departureTimeLabel4;
    private javax.swing.JLabel departureTimeLabel5;
    private javax.swing.JLabel notesLabel;
    private javax.swing.JTextField passengerCountField;
    private javax.swing.JLabel passengerCountLabel;
    private javax.swing.JTextField priceField1;
    private javax.swing.JTextField priceField2;
    private javax.swing.JTextField priceField3;
    private javax.swing.JTextField priceField4;
    private javax.swing.JTextField priceField5;
    private javax.swing.JButton payButton;
    private javax.swing.JRadioButton superAirJetRadioButton;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel orderDetailsLabel;
    private javax.swing.JRadioButton garudaRadioButton;
    private javax.swing.JRadioButton lionAirRadioButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
